[build]
  command = "npm run export"
  publish = "out"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"
JAMIFY_NEXT_ISR = "false"
JAMIFY_NEXT_FEATURE_IMAGES = "false"
JAMIFY_NEXT_INLINE_IMAGES = "false"